FIND_PROGRAM( CLANG clang /usr/bin )
FIND_PROGRAM( CLANG_PLUS clang++ /usr/bin )
FIND_PROGRAM( LLVM_LD llvm-ld /usr/bin )
FIND_PROGRAM( LLVM_AR llvm-ar /usr/bin )
FIND_PROGRAM( LLVM_NM llvm-nm /usr/bin )
 
IF ( CLANG AND CLANG_PLUS AND LLVM_LD AND LLVM_AR AND LLVM_NM )
	SET ( LLVM_FOUND TRUE )
ELSE ( CLANG AND CLANG_PLUS AND LLVM_LD AND LLVM_AR AND LLVM_NM )
	SET ( LLVM_FOUND FALSE )
ENDIF ( CLANG AND CLANG_PLUS AND LLVM_LD AND LLVM_AR AND LLVM_NM )

